image:
  name: node:8.10-alpine

pipelines:
  default:
    - step:
        name: Build and test
        caches:
          - node
        script:
          - export ENVIRONMENT=dev
          - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
          - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
          - export AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION

          - apk add --no-cache py-pip make bash git openssh-client jq
          - pip install awscli

          - make install

          - make clean
          - make install_production

    - step:
        name: Deploy
        deployment: test
        trigger: manual
        caches:
          - node
        script:
          - export ENVIRONMENT=dev
          - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
          - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
          - export AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION

          - apk add --no-cache py-pip make bash git openssh-client jq
          - pip install awscli

          - make install_production
          - make deploy
